### ISSUE TITLE
processingParams.csv

### ISSUE THREAD

**Issue by yhwu** [esherm/BushmanIntSites#15]
~/EAS/vectorSeqs/p746vector.fasta

change to p746vector.fasta

**Comment by esherm** [comment]
It is currently set to p746vector.fasta (at least as of commit 027c58750910ef6c2dc1ed3c8d5f2d0dab9522c1 )

https://github.com/esherm/intSiteCaller/blob/master/testCases/intSiteValidation/processingParams.csv
