### ISSUE TITLE
hiReadsProcessor package required

### ISSUE THREAD

**Issue by yhwu** [esherm/BushmanIntSites#17]

**Comment by esherm** [comment]
hiReadsProcessor is sourced in line 6 of intSiteLogic.R and is listed as dependency in README.md

https://github.com/esherm/intSiteCaller/blob/master/intSiteLogic.R#L6
https://github.com/esherm/intSiteCaller/blob/master/README.md

(as of commit c421c4fde3165df20d28dacd3d9ae9a199fab995)
