### ISSUE TITLE
codeDir

### ISSUE THREAD

**Issue by yhwu** [esherm/BushmanIntSites#19]
## to remove hard coded path

args <- commandArgs(trailingOnly = FALSE)
codeDir <- dirname(sub("--file=", "", grep("--file=", args, value=T)))
if ( length(codeDir) == 0 ) codeDir <- "/home/yinghua/projects/intSiteCaller"
stopifnot( length(list.files(path=codeDir, pattern="[intSiteLogic|programFlow].R"))>=2 )

**Comment by esherm** [comment]
Good idea - more flexibility is always better!
