### ISSUE TITLE
stop gfServer before start, randomize blat port

### ISSUE THREAD

**Issue by yhwu** [esherm/BushmanIntSites#21]
gfServer stop localhost $2
gfServer start localhost $2 -tileSize=11 -repMatch=112312 -maxDnaHits=20 -canStop $3 &

blatStartPort <- 5560 + Sys.getpid() %% 1000

**Comment by esherm** [comment]
I'd rather not stop the blat server on any given port in case somebody else on PMACS was doing blat on that port.  I'm thinking of a solution where during `postTrimReads` we figure out how many blat ports are needed, then start at the default (5560) and systematically check ports in ascending order to see if they're available. Then, once all the blat ports have been picked, actually call `alignSeqs`.

Randomly picking ports might result in collisions, which would cause problems if two different gfClients needed different reference genomes but accidently collided on the same gfServer, which can only accept a single reference genome.

**Comment by esherm** [comment]
This would also allow the `blatPort` argument in `PMACS_kickoff.R` to be removed
