### ISSUE TITLE
all GRanges objects should have seqinfo set for catching out of bounds errors

### ISSUE THREAD

**Issue by anatolydryga** [esherm/BushmanIntSites#4]
example:

load BSgenome.HSapiens (see random_site.R intSiteRetriever)

reference <- get_reference_genome("hg18")
human_seqinfo <- seqinfo(reference)

sites <- GRanges(
    seqnames=Rle(c("chr1", "chr11", "chrX", "chrY")),
    ranges=IRanges(start=c(100, 200, 300, 10000000), width=rep(1, 4)),
    strand=Rle(c("+", "-", "+", "+")),
    seqinfo=human_seqinfo
)

now all GRanges are valid

**Comment by esherm** [comment]
Resolved with commit f75bc2ce4629fca63109ad8800a5a38f5557432e

Still using file paths for reference genome 2bit files as saving a unique 2bit file from the BSGenome reference would be rather inefficient, especially if we want to allow multiple different reference genomes to be processed simultaneously
