### ISSUE TITLE
duplicate file PMACS_kickoff.R

### ISSUE THREAD

**Issue by yhwu** [esherm/BushmanIntSites#7]
PMACS_kickoff.R
intSiteValidation/PMACS_kickoff.R

**Comment by esherm** [comment]
This was duplicated so that the intSiteValidation directory could be its own free-standing test directory, independent of the code in development.  

I think git can handle symlinks reasonably gracefully, so perhaps making intSiteValidation/PMACS_kickoff.R a symlink to PMACS_kickoff.R would be best

**Comment by esherm** [comment]
Fixed by making intSiteValidation/PMACS_kickoff.R a symlink to PMACS_kickoff.R in 42e972a606e76b1cc2c8aa60b5c11d81394b2a6b
