### ISSUE TITLE
Push as many files to github as possible

### ISSUE THREAD

**Issue by esherm** [esherm/BushmanIntSites#9]
remove dependency on "~/EAS" in code

will have to re-write reference genome code to accept absolute file path since it's not feasible to check in entire reference genome to github.  Or perhaps save stuff directly from the BSgenome hg18 package each time?

**Comment by aubreybailey** [comment]
I vote BSGenome if you can.

**Comment by esherm** [comment]
Cool - looks like it's do-able and it won't add more than 2-3 minutes to the overall runtime of the program.  Just have to figure out how to handle some boundary cases with ambiguity codes.

**Comment by esherm** [comment]
Resolved with 3931b5f69c4c4c9672f851acf329898f1bc5b325

Only remaining dependency to local file structure is the codeDir variable in PMACS_kickoff.R to direct the rest of the program to the directory containing intSiteCaller. This makes more sense to me than requiring that important files be copied to each individual run directory.
